channels:
  sources: [symengine, conda-forge, defaults]
  targets:
    - [symengine, dev]

travis:
  secure:
    BINSTAR_TOKEN: DmbsI/b4ilneWoEh0Ts7gyTBtdqeryEFGmR+07arQTLXmqo5rt98dcwvX4NryzT0acub7u8d9XwxCvkrIAGRWNRexD9BDQqD1BBK/cqlMMTz1x7RY4TSx1r/P/37RSVVyhjgdcQHjl/qgZUYmXMy5uyAMr9zXv6GN+3UqjgR4z6GAKhGygPyRHSpjN+8Kv4021Wq97hNaB7qF6lJLTntwPqdKuI9FwylUaaNhhy6fr8sTgdqIuOghDBqNmIPZjHkvhOPNHrR95XaGO6NttVrwuO8JrgpzcGzwBKl1nkp3Hnwa7VY8FB6UUWiDaCX3IdDYeDfSU6DWVErzw89PzCXyN8G1L9x2+Qb0i8OeGD2UzWSXfAYU6/Q/NqcuVhzOsKgtqRfZUZCS3CdRaLDDnb0ZSDyIvfHJVPc2KZCkvHyjYLtZGjoCPZfjwIWPLdGieRedhEBQWOp1GVFY6+A7WdDfEonFaaGG4mAgWfx5FYP+gcTOehBNR6mOzvQ4kdHAgH4ma1bY9lLZdG3rCO5uBc48rYH0750T7+m3pH2DhHT7WVIES/fFXj6YbkunXFN8zYEHjfW0mKDi87pmnXfeOMVwumoFc/fFuik3DbTG18QOW0zDsyWwN4KsEQ1qIsT1pC5qeMAAh9Zk2xshAu72g7Yf9nGKPcJsoufICXLcmqUgu0=
appveyor:
  secure:
    BINSTAR_TOKEN: mnyKh9WUccsl/wEyLwP/ImhWItQ7cBiukFPSLwd52px18jRYq4SyL/ETYediXrUu
