channels:
  sources: [symengine, conda-forge, defaults]
  targets:
    - [symengine, dev]

travis:
  secure:
    BINSTAR_TOKEN: RuKc0R2skiePVdSQp6B2CgYi2r+H3PF7KK3RFiF6DTCeDigor01RYP3VAZqyzy06I5eyvKHgOj0384Bz1C+0hlYSS9M56E4fMTZbrVQU2fMcxC2ToYDWTsNSI7zPXbB5wD156OYsrzmcXo5cHVdSIXLc7Q3qQmFIjvJlDOmpA6di97DBGNfv67T6vnt/TheN+KM91S34PLTycW6shdEb6iUXscirZjH5CdhIqruafDVdv0NwYpAGP3oFuxlVVA2m84PvIAYaMKLdjGrPagXPP0LK4h5pmtf99A8zy0iJtsF0tzMQYkKaUDuWOub18F8JeJLqNn9lWb9fsvDfbP4NANKMD6P+Y22fAnZtLJ6QRBGc5QcBm4GnspFPDej3NCW9U80d+WeK7ALOxEzu759Obbw65Dxo84d05Hr7zPXr+NZs7rcvnyPtuiEgSln12LP5kZ+Fliu7uJmY/GW+9XpzAvCx/UMb6CB/fJWl36Eq2HkcFyRJsyv9mlN8kFYv6T1eTcbI95rNrMEHYtnqshaNdamszZ3lYiFhatDh7dQJ7rwI//YG+oGcLXLtGoNLa0LK+gsl0w43dmrsBz2X0dg7UqouEtlxq2rPjzWaLntJUOK5+rXpL21IedmEFWQTMBDqfnISZM8TCUyzO6ZO6bVyKhsMX61wTF0BiWTQTOYVjS4=
appveyor:
  secure:
    BINSTAR_TOKEN: mnyKh9WUccsl/wEyLwP/ImhWItQ7cBiukFPSLwd52px18jRYq4SyL/ETYediXrUu
